/**
 * FxSumo
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface AddSignalViewModel {
    title?: string;

    description?: string;

    actionID?: number;

    openPrice?: number;

    signalTypeID?: number;

    currencyPairID?: number;

    takeProfit?: number;

    stopLoss?: number;

    signalStatusID?: number;

    createdOn?: Date;

    youtubeURL?: string;

    wistiaURL?: string;

    pictureURL?: string;

}
