/**
 * FxSumo
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface SignalDetailsViewModel {
    id?: number;

    explanation?: string;

    description?: string;

    action?: string;

    openPrice?: number;

    signalType?: string;

    currency?: string;

    currencyInfo?: string;

    stopLoss?: number;

    takeProfit1?: number;

    takeProfit2?: number;

    takeProfit3?: number;

    takeProfit4?: number;

    signalStatus?: string;

    createdOn?: Date;

    youtubeURL?: string;

    wistiaURL?: string;

    imageURL?: string;

}
